//
// Created by benji on 06.06.26.
//

#ifndef RAYLIBPLAYGROUND_TEMPLATES_HPP
#define RAYLIBPLAYGROUND_TEMPLATES_HPP

inline const char *dts =
"// print a message\n"
"declare function Print(message: string): void;\n"
"\n"
"// Beginning of the drawLoop\n"
"declare function BeginDrawing(): void;\n"
"// End of the DrawLoop\n"
"declare function EndDrawing(): void;\n"
"// Start 3d rendering mode\n"
"declare function BeginMode3D(camera: object): void;\n"
"// End 3d rendering mode\n"
"declare function EndMode3D(): void;\n"
"// Clear the background (normally at the beginning of the drawLoop)\n"
"declare function ClearBackground(color: object): void;\n"
"// Draw the current frames per second\n"
"declare function DrawFPS(x: number, y: number): void;\n"
"// Pause the application for a given time\n"
"declare function Sleep(duration: number): void;\n"
"// Get the sine\n"
"declare function sin(x: number): number;\n"
"// Get the cosine\n"
"declare function cos(x: number): number;\n"
"\n"
"// Launch in headless mode (no rendering)\n"
"declare function Headless(): void;\n"
"// Get the frame time\n"
"declare function GetFrameTime(): number;\n"
"// Get the window width\n"
"declare function GetScreenWidth(): number;\n"
"// Get the window height\n"
"declare function GetScreenHeight(): number;\n"
"// Maximize the window\n"
"declare function MaximizeWindow(): void;\n"
"// Set the title of the application window\n"
"declare function SetWindowTitle(title: string): void;\n"
"\n"
"// Closes the window\n"
"declare function CloseWindow(): void;\n"
"// Get the char pressed (check [0] of the returned string)\n"
"declare function GetCharPressed(): string;\n"
"\n"
"// Check if a key is held down\n"
"declare function IsKeyDown(key: string): boolean;\n"
"// Check if a key just got pressed\n"
"declare function IsKeyPressed(key: string): boolean;\n"
"\n"
"// Get the mouse X position\n"
"declare function GetMouseX(): number;\n"
"// Get the mouse Y position\n"
"declare function GetMouseY(): number;\n"
"// Get Mouse movement between current and last frame (x axis)\n"
"declare function GetMouseDeltaX(): number;\n"
"// Get Mouse movement between current and last frame (y axis)\n"
"declare function GetMouseDeltaY(): number;\n"
"\n"
"// Check if a mouse button is down\n"
"declare function IsMouseButtonDown(button: number): number;\n"
"// Check if a mouse button just got pressed\n"
"declare function IsMouseButtonPressed(button: number): number;\n"
"// Check how much the mousewheel was moved\n"
"declare function GetMouseWheelMove(): number;\n"
"\n"
"// Draw a Circle\n"
"declare function DrawCircle(): void;\n"
"// Draw a Rectangle\n"
"declare function DrawRectangle(): void;\n"
"// Draw a Rectangle (Lines only)\n"
"declare function DrawRectangleLines(): void;\n"
"// Draw a text\n"
"declare function DrawText(text: string, xPos: number, yPos: number): void;\n"
"// Draw an image\n"
"declare function DrawImage(): void;\n"
"\n"
"// Draw a 3D grid\n"
"declare function DrawGrid(slices: number, spacing: number): void;\n"
"// Draw a 3D Cube\n"
"declare function DrawCube(position: object, width: number, height: number, length: number): void;\n"
"// Draw a 3D Cube (from vectors)\n"
"declare function DrawCubeV(): void;\n"
"// Draw a 3D Cube (from vectors), just wires (broken)\n"
"declare function DrawCubeWires(): void;\n"
"// Load a shader from the files system, get back a shader id\n"
"declare function LoadShader(vertexPath: string, fragmentPath: string): number;\n"
"// Load a shaders Uniform location\n"
"declare function GetUniformLocation(shaderID: number, uniform: string): number;\n"
"// Set the value of a shader uniform\n"
"declare function SetUniform(shaderID: number, uniformLocation: number, value: any): void;\n"
"// Start using a shader\n"
"declare function BeginShader(shaderID: number): void;\n"
"// Stop using any active shaders\n"
"declare function EndShader(): void;";

inline const char *script_template_src =
    "var player;\n"
    "var velocity;\n"
    "var circleColor = {\n"
    "   r: 50,\n"
    "   g: 50,\n"
    "   b: 255,\n"
    "   a: 255\n"
    "};\n\n"
    "velocity = { x: 200, y: 200 }\n\n"
    "function onStart() {\n"
    "   Print(\"Starting\");\n"
    "   SetTargetFPS(60);\n"
    "   \n"
    "   player = { x: 0, y: 0 }\n"
    "}\n\n"
    "function onReady() {}\n"
    "function onFrame() {\n"
    "    BeginDrawing();\n"
    "    ClearBackground({r: 0, g: 0, b: 0, a: 255});\n"
    "    //DrawFPS(10, 10);\n"
    "    if (player.x >= GetScreenWidth()) { velocity.x *= -1; }\n"
    "    if (player.y >= GetScreenHeight()) { velocity.y *= -1; }\n"
    "    if (player.x <= 0) { velocity.x *= -1; }\n"
    "    if (player.y <= 0) { velocity.y *= -1; }\n"
    "    player.x += velocity.x * GetFrameTime();\n"
    "    player.y += velocity.y * GetFrameTime();\n"
    "    DrawCircle(player.x, player.y, 20, circleColor);\n"
    "    EndDrawing();\n"
    "}\n";

// later create a template
inline void create_script_template(const char *projectName) {
    std::ofstream script(projectName);
    script << script_template_src;
}

inline void create_dts_template() {
    std::ofstream dts_file(".d.ts");
    dts_file << dts;
}

#endif //RAYLIBPLAYGROUND_TEMPLATES_HPP
