#ifndef RAYLIBPLAYGROUND_TEMPLATES_HPP
#define RAYLIBPLAYGROUND_TEMPLATES_HPP

#include <iostream>

inline const char *dts = 
// get individual args\n"
"declare function Args(pos: number): string;\n"
"// get the amount of args\n"
"declare function ArgcCount(): number;\n"
"// print a message\n"
"declare function Print(message: string): void;\n"
"// Beginning of the drawLoop\n"
"declare function BeginDrawing(): void;\n"
"// End of the DrawLoop\n"
"declare function EndDrawing(): void;\n"
"// Start 3d rendering mode\n"
"declare function BeginMode3D(camera: { position: {x: number, y: number, z: number}, target: {x: number, y: number, z: number}, up: {x: number, y: number, z: number}, fovy: number }): void;\n"
"// End 3d rendering mode\n"
"declare function EndMode3D(): void;\n"
"// Clear the background (normally at the beginning of the drawLoop)\n"
"declare function ClearBackground(color: object): void;\n"
"// Draw the current frames per second\n"
"declare function DrawFPS(x: number, y: number): void;\n"
"//Set the desired framerate\n"
"declare function SetTargetFPS(fps: number):void;\n"
"// Pause the application for a given time\n"
"declare function Sleep(duration: number): void;\n"
"// Get the sine\n"
"declare function Sin(x: number): number;\n"
"// Get the cosine\n"
"declare function Cos(x: number): number;\n"
"// Launch in headless mode (no rendering)\n"
"declare function Headless(): void;\n"
"// Get the frame time\n"
"declare function GetFrameTime(): number;\n"
"// Get the window width\n"
"declare function GetScreenWidth(): number;\n"
"// Get the window height\n"
"declare function GetScreenHeight(): number;\n"
"// Resize the window\n"
"declare function ResizeWindow(width: number, height: number): void;\n"
"// Maximize the window\n"
"declare function MaximizeWindow(): void;\n"
"// Set the title of the application window\n"
"declare function SetWindowTitle(title: string): void;\n"
"// Allow resizing\n"
"declare function AllowWindowResize(): void;\n"
"\n"
"// Closes the window\n"
"declare function CloseWindow(): void;\n"
"// Get the char pressed (check [0] of the returned string)\n"
"declare function GetCharPressed(): string;\n"
"\n"
"// Check if a key is held down\n"
"declare function IsKeyDown(key: string): boolean;\n"
"// Check if a key just got pressed\n"
"declare function IsKeyPressed(key: string): boolean;\n"
"// Get the mouse X position\n"
"declare function GetMouseX(): number;\n"
"// Get the mouse Y position\n"
"declare function GetMouseY(): number;\n"
"// Get Mouse movement between current and last frame (x-axis)\n"
"declare function GetMouseDeltaX(): number;\n"
"// Get Mouse movement between current and last frame (y-axis)\n"
"declare function GetMouseDeltaY(): number;\n"
"\n"
"// Check if a mouse button is down\n"
"declare function IsMouseButtonDown(button: number): number;\n"
"// Check if a mouse button just got pressed\n"
"declare function IsMouseButtonPressed(button: number): number;\n"
"// Check how much the mousewheel was moved\n"
"declare function GetMouseWheelMove(): number;\n"
"\n"
"// Draw a Line\n"
"declare function DrawLine(startX: number, starty: number, endX: number, endY: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Circle\n"
"declare function DrawCircle(x: number, y: number, radius: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Rectangle\n"
"declare function DrawRectangle(x: number, y: number, width: number, height: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Rectangle (Lines only)\n"
"declare function DrawRectangleLines(): void;\n"
"// Draw a text\n"
"declare function DrawText(text: string, xPos: number, yPos: number, fontSize: number, tint: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw an image\n"
"declare function DrawImage(filePath: string, posX: number, posY: number, width: number, height: number): void;\n"
"// Draw a 3D grid\n"
"declare function DrawGrid(slices: number, spacing: number): void;\n"
"// Draw a 3D Cube\n"
"declare function DrawCube(position: object, width: number, height: number, length: number): void;\n"
"// Draw a 3D Cube (from vectors)\n"
"declare function DrawCubeV(): void;\n"
"// Draw a 3D Cube (from vectors), just wires (broken)\n"
"declare function DrawCubeWires(): void;\n"
"// Load a 3D model\n"
"declare function LoadModel(path: string): number;\n"
"// Draw a mesh\n"
"declare function DrawMesh(meshID: number): void;\n"
"// Draw a model\n"
"declare function DrawModel(meshID: number): void;\n"
"// Load a shader from the files system, get back a shader id\n"
"declare function LoadShader(vertexPath: string, fragmentPath: string): number;\n"
"// Load a shaders Uniform location\n"
"declare function GetUniformLocation(shaderID: number, uniform: string): number;\n"
"// Set the value of a shader uniform\n"
"declare function SetUniform(shaderID: number, uniformLocation: number, value: any): void;\n"
"// Start using a shader\n"
"declare function BeginShader(shaderID: number): void;\n"
"// Stop using any active shaders\n"
"declare function EndShader(): void;\n"
"// Get the last modified time of a file\n"
"declare function GetFileModTime(path: string): number;\n"
"// Set the font to use\n"
"declare function SetFont(path: string): void;\n"
"// Open a file to read (returns file id)\n"
"declare function OpenFile(path: string): number;\n"
"declare function CloseFile(fileID: number): void;\n"
"// Read a file from a file\n"
"declare function GetLine(fileID: number, maxCharacters: number): number;\n"
"// Check if end of file has been reached\n"
"declare function AtEOF(fileID: number): boolean;\n"
"// Rewind a file (reset seek) (actually reopen)\n"
"declare function Rewind(fileID: number): void;\n"
"// Write string to a file\n"
"declare function Save(filePath: string, content: string);\n"
"\n"
"// Host a server\n"
"declare function Host(port: number): void;\n"
"// Check if app is hosting\n"
"declare function IsHosting(): boolean;\n"
"// Connect to a server\n"
"declare function Host(address: string): void;\n"
"// Send a message (server sends to all clients, clients send to the server)\n"
"declare function SendMessage(message: string): void;\n"
"\n"
"// Open a serial port\n"
"declare function OpenSerial(path: string, baudrate: number): void;\n"
"// Write a message to the opened serial port\n"
"declare function WriteSerial(message: string): void;\n"
"declare function WriteSerial(message: number): void;\n"
"// Check if serial is already opened\n"
"declare function IsSerialOpen(): boolean;\n"
"// Try to reopen serial if originally failed to do so\n"
"declare function SerialRetry(): void;\n"
"declare function ReadSerial(): string;\n"
"// Get the width of text\n"
"declare function MeasureTextW(text: string, fontSize): number;\n"
"// Get the height of text\n"
"declare function MeasureTextH(text: string, fontSize): number";


const char *script_template_src = 
"function onStart() {\n"
"    Print(\"Starting\");\n"
"    SetTargetFPS(60);\n"
"}\n"
"\n"
"function onReady() {}\n"
"function onFrame() {\n"
"    BeginDrawing();\n"
"    ClearBackground({r: 0, g: 0, b: 0, a: 255});\n"
"\n"
"    EndDrawing();\n"
"}";

// later create a template
inline void create_script_template(const char *projectName) {
    std::ofstream script(projectName);
    script << script_template_src;
}
inline void create_dts_template() {
    std::ofstream dts_file(".d.ts");
    dts_file << dts;
}
#endif //RAYLIBPLAYGROUND_TEMPLATES_HPP