#ifndef RAYLIBPLAYGROUND_TEMPLATES_HPP
#define RAYLIBPLAYGROUND_TEMPLATES_HPP

#include <iostream>

inline const char *dts = 
// get individual args\n"
"declare function Args(pos: number): string;\n"
"// get the amount of args\n"
"declare function ArgcCount(): number;\n"
"// print a message\n"
"declare function Print(message: string): void;\n"
"// Beginning of the drawLoop\n"
"declare function BeginDrawing(): void;\n"
"// End of the DrawLoop\n"
"declare function EndDrawing(): void;\n"
"// Start 3d rendering mode\n"
"declare function BeginMode3D(camera: { position: {x: number, y: number, z: number}, target: {x: number, y: number, z: number}, up: {x: number, y: number, z: number}, fovy: number }): void;\n"
"// End 3d rendering mode\n"
"declare function EndMode3D(): void;\n"
"// Clear the background (normally at the beginning of the drawLoop)\n"
"declare function ClearBackground(color: object): void;\n"
"// Draw the current frames per second\n"
"declare function DrawFPS(x: number, y: number): void;\n"
"//Set the desired framerate\n"
"declare function SetTargetFPS(fps: number):void;\n"
"// Pause the application for a given time\n"
"declare function Sleep(duration: number): void;\n"
"// Get the sine\n"
"declare function Sin(x: number): number;\n"
"// Get the cosine\n"
"declare function Cos(x: number): number;\n"
"// Launch in headless mode (no rendering)\n"
"declare function Headless(): void;\n"
"// Get the frame time\n"
"declare function GetFrameTime(): number;\n"
"// Get the window width\n"
"declare function GetScreenWidth(): number;\n"
"// Get the window height\n"
"declare function GetScreenHeight(): number;\n"
"// Resize the window\n"
"declare function ResizeWindow(width: number, height: number): void;\n"
"// Maximize the window\n"
"declare function MaximizeWindow(): void;\n"
"// Set the title of the application window\n"
"declare function SetWindowTitle(title: string): void;\n"
"// Allow resizing\n"
"declare function AllowWindowResize(): void;\n"
"\n"
"// Closes the window\n"
"declare function CloseWindow(): void;\n"
"// Get the char pressed (check [0] of the returned string)\n"
"declare function GetCharPressed(): string;\n"
"\n"
"// Check if a key is held down\n"
"declare function IsKeyDown(key: string): boolean;\n"
"// Check if a key just got pressed\n"
"declare function IsKeyPressed(key: string): boolean;\n"
"// Get the mouse X position\n"
"declare function GetMouseX(): number;\n"
"// Get the mouse Y position\n"
"declare function GetMouseY(): number;\n"
"// Get Mouse movement between current and last frame (x-axis)\n"
"declare function GetMouseDeltaX(): number;\n"
"// Get Mouse movement between current and last frame (y-axis)\n"
"declare function GetMouseDeltaY(): number;\n"
"\n"
"// Check if a mouse button is down\n"
"declare function IsMouseButtonDown(button: number): number;\n"
"// Check if a mouse button just got pressed\n"
"declare function IsMouseButtonPressed(button: number): number;\n"
"// Check how much the mousewheel was moved\n"
"declare function GetMouseWheelMove(): number;\n"
"\n"
"// Draw a Line\n"
"declare function DrawLine(startX: number, starty: number, endX: number, endY: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Circle\n"
"declare function DrawCircle(x: number, y: number, radius: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Rectangle\n"
"declare function DrawRectangle(x: number, y: number, width: number, height: number, color: {r: number, g: number, b: number, a: number}): void;\n"
"// Draw a Rectangle (Lines only)\n"
"declare function DrawRectangleLines(): void;\n"
"// Draw a text\n"
"declare function DrawText(text: string, xPos: number, yPos: number): void;\n"
"// Draw an image\n"
"declare function DrawImage(filePath: string, posX: number, posY: number, width: number, height: number): void;\n"
"// Draw a 3D grid\n"
"declare function DrawGrid(slices: number, spacing: number): void;\n"
"// Draw a 3D Cube\n"
"declare function DrawCube(position: object, width: number, height: number, length: number): void;\n"
"// Draw a 3D Cube (from vectors)\n"
"declare function DrawCubeV(): void;\n"
"// Draw a 3D Cube (from vectors), just wires (broken)\n"
"declare function DrawCubeWires(): void;\n"
"// Load a 3D model\n"
"declare function LoadModel(path: string): number;\n"
"// Draw a mesh\n"
"declare function DrawMesh(meshID: number): void;\n"
"// Draw a model\n"
"declare function DrawModel(meshID: number): void;\n"
"// Load a shader from the files system, get back a shader id\n"
"declare function LoadShader(vertexPath: string, fragmentPath: string): number;\n"
"// Load a shaders Uniform location\n"
"declare function GetUniformLocation(shaderID: number, uniform: string): number;\n"
"// Set the value of a shader uniform\n"
"declare function SetUniform(shaderID: number, uniformLocation: number, value: any): void;\n"
"// Start using a shader\n"
"declare function BeginShader(shaderID: number): void;\n"
"// Stop using any active shaders\n"
"declare function EndShader(): void;\n"
"// Get the last modified time of a file\n"
"declare function GetFileModTime(path: string): number;\n"
"// Set the font to use\n"
"declare function SetFont(path: string): void;\n"
"// Open a file to read (returns file id)\n"
"declare function OpenFile(path: string): number;\n"
"// Read a file from a file\n"
"declare function GetLine(fileID: number, maxCharacters: number): number;\n"
"// Check if end of file has been reached\n"
"declare function AtEOF(fileID: number): boolean;\n"
"// Rewind a file (reset seek) (actually reopen)\n"
"declare function Rewind(fileID: number): void;\n"
"// Write string to a file\n"
"declare function Save(filePath: string, content: string);\n"
"\n"
"// Host a server\n"
"declare function Host(port: number): void;\n"
"// Check if app is hosting\n"
"declare function IsHosting(): boolean;\n"
"// Connect to a server\n"
"declare function Host(address: string): void;\n"
"// Send a message (server sends to all clients, clients send to the server)\n"
"declare function SendMessage(message: string): void;\n"
"\n"
"// Open a serial port\n"
"declare function OpenSerial(path: string, baudrate: number): void;\n"
"// Write a message to the opened serial port\n"
"declare function WriteSerial(message: string): void;\n"
"declare function WriteSerial(message: number): void;\n"
"// Check if serial is already opened\n"
"declare function IsSerialOpen(): boolean;\n"
"// Try to reopen serial if originally failed to do so\n"
"declare function SerialRetry(): void;\n"
"declare function ReadSerial(): string";


const char *script_template_src = 
"var player1;\n"
"var player2;\n"
"var ball;\n"
"var velocity;\n"
"var reloadCount;\n"
"var circleColor = {\n"
"    r: 200,\n"
"    g: 50,\n"
"    b: 255,\n"
"    a: 255\n"
"};\n"
"\n"
"var autoplay = false;\n"
"var rectColor = {\n"
"    r: 200,\n"
"    g: 255,\n"
"    b: 255,\n"
"    a: 255\n"
"};\n"
"\n"
"var playerWidth = 10;\n"
"var playerHeight = 100;\n"
"var padding = 10;\n"
"var ballRadius = 20;\n"
"var level = 1;\n"
"\n"
"function onStart() {\n"
"    print(\"Starting\");\n"
"    SetTargetFPS(100);\n"
"}\n"
"\n"
"\n"
"//reloadCount++;\n"
"//velocity = { x: 100, y: 100 }\n"
"\n"
"//player1.score = 0;\n"
"//player2.score = 0;\n"
"\n"
"function onReady() {\n"
"    reloadCount = 0;\n"
"    SetWindowTitle(\"PONG in RaylibPlayground!\");\n"
"    player1 = { x: padding, y: 0, score: 0}\n"
"    player2 = { x: GetScreenWidth()-padding-playerWidth, y: 0, score: 0 }\n"
"    ball = {\n"
"        x: 100,\n"
"        y: 100\n"
"    }\n"
"}\n"
"\n"
"function onFrame() {\n"
"    if (ball.x >= GetScreenWidth()-ballRadius-playerWidth-padding) {\n"
"        if (player2.y < ball.y && player2.y+playerHeight > ball.y) {\n"
"            ball.x = GetScreenWidth()-ballRadius-playerWidth-padding;\n"
"            level++;\n"
"            velocity.x *= -1;\n"
"        } else {\n"
"            level = 1;\n"
"            velocity.x = 100;\n"
"            velocity.y = 100;\n"
"            ball.x = 100;\n"
"            ball.y = 100;\n"
"            player1.score++;\n"
"        }\n"
"    }\n"
"    if (ball.y >= GetScreenHeight()-ballRadius)   { ball.y = GetScreenHeight()-ballRadius; velocity.y *= -1; }\n"
"    if (ball.x <= playerWidth+padding+ballRadius) {\n"
"        if (player1.y < ball.y && player1.y+playerHeight > ball.y) {\n"
"            ball.x = playerWidth+padding+ballRadius;\n"
"            velocity.x *= -1; level++;\n"
"        } else {\n"
"            //if player1 messes up\n"
"            level = 1;\n"
"            velocity.x = 100;\n"
"            velocity.y = 100;\n"
"            ball.x = 100;\n"
"            ball.y = 100;\n"
"            player2.score++;\n"
"        }\n"
"    }\n"
"    if (ball.y <= ballRadius) { ball.y = ballRadius; velocity.y *= -1; }\n"
"\n"
"    var delta = GetFrameTime();\n"
"\n"
"    var levelMult = ( 1 + (level * (.5-level*.001) ));\n"
"    ball.x += velocity.x  * levelMult * delta;\n"
"    ball.y += velocity.y  * levelMult * delta;\n"
"\n"
"    BeginDrawing();\n"
"    ClearBackground({r: 255, g: 255, b: 255, a: 255});\n"
"    DrawFPS(GetScreenWidth() / 2 + 5, 10);\n"
"    //SetTargetFPS(30);\n"
"\n"
"    //Draw Middle Line\n"
"    DrawRectangle(GetScreenWidth()/2, 0, 1, GetScreenHeight(), {r: 100, g: 100, b: 100, a: 255});\n"
"\n"
"    DrawCircle(ball.x, ball.y, ballRadius, {r: 10, g: 10, b: 250, a: 255-ball.x/20});\n"
"    DrawCircle(ball.x, ball.y, ballRadius, {r: 200, g: 10, b: 10, a: ball.x/5});\n"
"\n"
"    if (IsKeyDown(\"w\"))    { player1.y -= 4; }\n"
"    if (IsKeyDown(\"s\"))    { player1.y += 4; }\n"
"    if (IsKeyDown(\"up\"))   { player2.y -= 4; }\n"
"    if (IsKeyDown(\"down\")) { player2.y += 4; }\n"
"\n"
"    if (IsKeyPressed(\"space\")) { autoplay = !autoplay; }\n"
"\n"
"    //Draw Left player1\n"
"    DrawRectangle(player1.x, player1.y, playerWidth, playerHeight, {r: 10, g: 10, b: 250, a: 255});\n"
"\n"
"    //Draw Right player2\n"
"    DrawRectangle(player2.x, player2.y, playerWidth, playerHeight, {r: 200, g: 10, b: 10, a: 255});\n"
"\n"
"    //auto playe\n"
"    if (autoplay) {\n"
"        player1.y = ball.y-playerHeight/2;\n"
"        player2.y = ball.y-playerHeight/2;\n"
"    }\n"
"\n"
"    DrawText(\"\"+player1.score+\":\"+player2.score+\"\nLevel: \"+level, GetScreenWidth()/2-25, 30, 40, {r: 20, g: 200, b: 10, a: 255});\n"
"\n"
"    EndDrawing();\n"
"}\n"
"";

// later create a template
inline void create_script_template(const char *projectName) {
    std::ofstream script(projectName);
    script << script_template_src;
}
inline void create_dts_template() {
    std::ofstream dts_file(".d.ts");
    dts_file << dts;
}
#endif //RAYLIBPLAYGROUND_TEMPLATES_HPP